RemoteControlServer/Controllers/DeviceController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Core.Types;
using RemoteControlServer.BusinessLogic.Communicators;
using RemoteControlServer.BusinessLogic.Database.Models;
using RemoteControlServer.BusinessLogic.Models;
using RemoteControlServer.BusinessLogic.Repository.DbRepository;
using RemoteControlServer.BusinessLogic.Services;
using RemoteControlServer.ViewModels;
using System.IO;
using System.Security.Claims;

namespace RemoteControlServer.Controllers
{
    [Authorize]
    public class DeviceController : Controller
    {
        private readonly ILogger<DeviceController> logger;
		private readonly UserDevicesService devicesService;
		private readonly IDbRepository dbRepository;

        public DeviceController(ILogger<DeviceController> logger, UserDevicesService devicesService, IDbRepository dbRepository)
        {
            this.logger = logger;
			this.devicesService = devicesService;
			this.dbRepository = dbRepository;
        }

        [HttpGet("Devices")]
        public async Task<IActionResult> Devices()
        { 
            User user = await GetUserAsync().ConfigureAwait(false);
            return View(new List<UserDevice>(await devicesService.GetUserDevicesAsync(user.Id).ConfigureAwait(false)));
		}

        [HttpGet("[controller]/{id}")]
        public async Task<IActionResult> Device(int id)
        {
            User user = await GetUserAsync().ConfigureAwait(false);
            if (!user.Devices.Any(x => x.Id == id))
            {
                return Forbid();
            }

            UserDevice userDevice = await devicesService.GetUserDeviceAsync(id).ConfigureAwait(false);
            return View(userDevice);
        }

		[HttpGet("DeviceFolder/{id}/{*path}")]
        public async Task<IActionResult> DeviceFolder(int id, string path)
        {
            User user = await GetUserAsync().ConfigureAwait(false);
            if (!user.Devices.Any(x => x.Id == id)) 
            {
                return Forbid();
            }

            UserDevice userDevice = await devicesService.GetUserDeviceAsync(id).ConfigureAwait(false);
            DeviceFolderViewModel model = new DeviceFolderViewModel(userDevice, path);            
            return View(model);           
        }

        private Task<User> GetUserAsync()
        {
            int id = int.Parse(User.FindFirstValue(ClaimTypes.Name));
            return dbRepository.Users.FindByIdAsync(id);
        }
    }
}

RemoteControlServer/Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RemoteControlServer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />    
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/lib/dataTables/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<style>
    body {
        background: black;
        color: #171A1FFF;
    }
</style>
<body>
    <main role="main">
        @RenderBody()
    </main>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>    
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @* <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.10/jquery.validate.unobtrusive.min.js"></script> *@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RemoteControlServer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RemoteControlServer</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/lib/dataTables/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    @if(ViewData["white"] is not bool b || !b)
    {
        <style>
            body{
                background: black;
                color: #171A1FFF;
            }
        </style>
    }
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">RemoteControl</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Device" asp-action="Devices">Подключенные устройства</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>    
        <main role="main" class="pb-3">
            @RenderBody()
        </main>    

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - RemoteControlServer - <a asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/dataTables/js/jquery.dataTables.min.js"></script>
    @* <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"></script> *@
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>    
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>